<robot name="radar" xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- 雷达 -->
    <link name="laser_link">
			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<mass value="0" />
				<inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<mesh filename="package://carmodel/meshes/radar_link.STL" />
				</geometry>
				<material name="">
					<color rgba="0.79216 0.81961 0.93333 1" />
				</material>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<mesh filename="package://carmodel/meshes/radar_link.STL" />
				</geometry>
			</collision>
		</link>
		<joint name="laser_joint" type="fixed">
			<origin xyz="0.040036 0 0.3" rpy="0 0 0" />
			<parent link="base_link" />
			<child link="laser_link" />
			<axis xyz="0 -1 0" />
		</joint>
		<gazebo reference="laser_link">
			<sensor type="ray" name="laser">
				<pose>0 0 0 0 0 0</pose>
				<visualize>false</visualize>
				<update_rate>8</update_rate>
				<ray>
					<scan>
						<horizontal>
							<samples>360</samples>
							<resolution>1</resolution>
							<min_angle>-3.14</min_angle>
							<max_angle>3.14</max_angle>
						</horizontal>
					</scan>
					<range>
						<min>0.10</min>
						<max>10.0</max>
						<resolution>0.01</resolution>
					</range>
					<noise>
						<type>gaussian</type>
						<mean>0.0</mean>
						<stddev>0.01</stddev>
					</noise>
				</ray>
				<plugin name="gazebo_laser" filename="libgazebo_ros_laser.so">
					<topicName>scan</topicName>
					<frameName>agv0/laser_link</frameName>
				</plugin>
			</sensor>
		</gazebo>
  
  </robot>
  

<!-- 


    激光雷达插件 
    <gazebo reference="${prefix}_laser_link">
      	<sensor type='ray' name='ray_sensor'>
        	<pose>0 -${laser_z_offset + laser_z_mount_offset + laser_z_mount_size /2 } -${laser_x_offset + laser_x_mount_offset + laser_x_mount_size /2 } -${laser_pitch_angle + pi /2 } -${laser_yaw_angle + pi /2 } -${laser_roll_angle}</pose>
        	<visualize>${visualize_laserscan}</visualize>
        	<update_rate>${update_rate}</update_rate>
        	<ray>
          		<scan>
            		<horizontal>
              			<samples>${samples}</samples>
              			<resolution>${resolution}</resolution>
              			<min_angle>${min_angle}</min_angle> 
              			<max_angle>${max_angle}</max_angle> 
            		</horizontal> 
          		</scan> 
          	
          	<range> -->